# Generated by Django 4.2 on 2024-05-07 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0003_filme_textolivre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='textolivre',
        ),
    ]
